library(testthat)
source("init.R")
source(file.path('model', 'model.R'))
source(file.path('tests', 'function_test_predictor.R'))
test_dir(file.path('tests', 'testthat'))
#auto_test('.', 'tests/testthat')
#test_dir(file.path('tests', 'testthat'))